
# html lang   # HTML lang
language   语言: zh-CN   语言:应用

# main menu navigation   #主菜单导航
menu   菜单:
  Home   首页: index.html   : index . html
  Archives   档案: archives   档案:档案
  Tags   标签: tags   标签:标签
  Categories   类别: categories   类别:类别
  About   关于: about   关于:
  Github: https://github.com/stiekel

social   社会:
  GitHub: https://github.com/stiekel
  Weibo   微博: http微博微博:http://weibo.com/sidcn:http://weibo.com/sidcn://weibo.com/sidcn
  M   米: histkc@gmail.com

# homepage article list size, 0 to hide list in homepage#主页文章列表大小，0隐藏列表在主页
homepageArticleCount: 3

# Google analytics   #谷歌分析
google_analytics: false   假
# Baidu tongji   # 百度通记
baidu_analytics: false   假
# Disqus
disqus_shortname:
# Uyan
uyan_id:
# jiaThis id
# if you want to change the style of jiaThis, please go to chage the following file:#如果您想更改jiaThis的样式，请转到更改以下文件:
# theme/random/layouts/includes/jiathis.swig#主题/随机/布局包括/ jiathis.swig
jiaThis_uid: 
jiathisConfig:
  data_track_clickback: true   真正的
  summary   总结: ""   ＂＂
  showClose: true
  shortUrl: false
  hideMore: false

# Valine comments https://valine.js.org
valine:
  enable: false # set true if you want to use
  appId: #your leancloud appId
  appKey: #your leancloud appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: # valine comment input placeholder(like: Please leave your footprints )
  avatar: robohash # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: false # valine verify code (true/false)
  notify: true # valine mail notify (true/false) 
  lang: en
  visit_analytics: true

# gitalk comments https://github.com/gitalk/gitalk
gitalk:
  enable: false
  clientID: clientID
  clientSecret: clientSecret
  repo: gitalk-comments
  owner: github-username

# Miscelaneous
favicon: /hollow.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/random.css
- /css/vegas.min.css
- /css/highlight-railscasts.css
- /css/jquery.fancybox.css
- /css/iconfont/iconfont.css
- /css/jquery.fancybox-thumbs.css
- /css/plyr.css

# scripts loaded in the end of the body
scripts:
- /js/jquery-3.6.4.min.js
- /js/vegas.min.js
- /js/random.js
- /js/highlight.pack.js
- /js/jquery.mousewheel.pack.js
- /js/jquery.fancybox.pack.js
- /js/jquery.fancybox-thumbs.js
- /js/plyr.js

# ignore visitor statistics on special server, for example on you local computer or debugging server
isIgnoreSpecialHostVisitor: true
ignoreHostList:
  - localhost
  - 127.0.0.1

# if you want to turn off the background images, pleaase set this value as true
turnoffBackgroundImage: 
  # home page
  index: false
  # arcihve / categories / tags
  post_list: false
  # post and page
  post: false
# when you turn off backgrounds, you can set a background color.
backgroundColor: 34495E
 
backgroundImages:
  - https://unsplash.it/__width__/__height__?random&t=6&gravity=center
  - https://unsplash.it/__width__/__height__?random&t=6&gravity=center
  - https://unsplash.it/__width__/__height__?random&t=6&gravity=center
  - https://unsplash.it/__width__/__height__?random&t=6&gravity=center
  - https://unsplash.it/__width__/__height__?random&t=6&gravity=center
vegasConfig:
  # more about config http://vegas.jaysalvat.com/documentation/settings/
  # animation: 'random'
  # transition: 'swirlRight'
  preload­Image: true
  transition:
    - slideLeft2
    - slideRight2
    - swirLeft
    - swirRight
    - flash
  animation­Duration: 100
  timer: false
  delay: 10000
  shuffle: true
  count: 12

unsplashConfig:
  # more about config on https://unsplash.it/
  # blur: true
  gravity: 'center' # north, east, south, west, center
  # greyscale: true

avatar: images/blog-avatar.png

# do not like fancybox, set this as false, this will turn it off
fancybox: true

# set the visibility of hide button in left bottom.
hideButtonVisibility: true
