
# html lang   # HTML lang
language   语言: zh-CN   语言   语言:应用:应用

# main menu navigation   #主菜单导航
menu   菜单:
  Home   首页: index.html      : index . html: index . html
  Archives   档案: archives   档案   档案:档案:档案
  Tags   标签: tags   标签   标签:标签:标签
  Categories   类别: categories   类别   类别:类别:类别
  About   关于: about   关于   关于::
  Github: https://github.com/stiekel

social   社会:
  GitHub: https://github.com/stiekel
  Weibo   微博: http微博微博:http://weibo.com/sidcn:http://weibo.com/sidcn://weibo.com/sidcn
  M   米: histkc@gmail.com

# homepage article list size, 0 to hide list in homepage#主页文章列表大小，0隐藏列表在主页
homepageArticleCount: 3

# Google analytics   #谷歌分析
google_analytics: false   假
# Baidu tongji   # 百度通记
baidu_analytics: false   假
# Disqus
disqus_shortname:
# Uyan
uyan_id:
# jiaThis id
# if you want to change the style of jiaThis, please go to chage the following file:#如果您想更改jiaThis的样式，请转到更改以下文件:
# theme/random/layouts/includes/jiathis.swig#主题/随机/布局包括/ jiathis.swig
jiaThis_uid: 
jiathisConfig:
  data_track_clickback: true   真正的
  summary   总结: ""   ＂＂
  showClose: true   真正的
  shortUrl: false   假
  hideMore: false   假

# Valine comments https://valine.js.org# Valine评论https://valine.js.org
valine   缬氨酸:
  enable   启用: false 启用:false #设置为true如果你想使用# set true if you want to use#设置为true，如果你想使用
  appId: #your leancloud appId   #你的leancloud应用
  appKey: #your leancloud appKey   #你的leancloud appKey
  guest_info: nick,mail,link Guest_info: nick,mail,link #valine comment header info#valine comment header info#valine注释头信息
  placeholder   占位符: # valine comment input placeholder(like: Please leave your footprints )# valine注释输入占位符(如:请留下您的足迹)
  avatar   《阿凡达》: robohash 头像：Robohash # Gravatar Style https://valine.js.org/avatar# gravatar style https://valine.js.org/avatar
  pageSize   页大小: 10 #评论列表页面大小# comment list page size#评论列表页面大小
  verify   验证: false 验证:false # valine验证码(true/false)# valine verify code (true/false)# valine验证码(true/false)
  notify   通知: true 通知:true # valine邮件通知(true/false)# valine mail notify (true/false) # valine邮件通知(true/false)
  lang   朗: en   长:
  visit_analytics: true   真正的

# gitalk comments https://github.com/gitalk/gitalk# gitalk评论https://github.com/gitalk/gitalk
gitalk   奇塔克:
  enable   启用: false   假
  clientID: clientID
  clientSecret: clientSecret
  repo   回购: gitalk-comments   回购:gitalk-comments
  owner   老板: github-username   老板:github-username

# Miscelaneous
favicon: /hollow.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/random.css
- /css/vegas.min.css
- /css/highlight-railscasts.css
- /css/jquery.fancybox.css
- /css/iconfont/iconfont.css
- /css/jquery.fancybox-thumbs.css
- /css/plyr.css

# scripts loaded in the end of the body
scripts:
- /js/jquery-3.6.4.min.js
- /js/vegas.min.js
- /js/random.js
- /js/highlight.pack.js
- /js/jquery.mousewheel.pack.js
- /js/jquery.fancybox.pack.js
- /js/jquery.fancybox-thumbs.js
- /js/plyr.js

# ignore visitor statistics on special server, for example on you local computer or debugging server
isIgnoreSpecialHostVisitor: true
ignoreHostList:
  - localhost
  - 127.0.0.1

# if you want to turn off the background images, pleaase set this value as true
turnoffBackgroundImage: 
  # home page
  index: false
  # arcihve / categories / tags
  post_list: false
  # post and page
  post: false
# when you turn off backgrounds, you can set a background color.
backgroundColor: 34495E
 
backgroundImages:
# - http://7te9fe.com1.z0.glb.clouddn.com/bgimg_1.jpg?imageView2/1/w/__width__/h/__height__
# - http://7te9fe.com1.z0.glb.clouddn.com/bgimg_2.jpg?imageView2/1/w/__width__/h/__height__
# - http://7te9fe.com1.z0.glb.clouddn.com/bgimg_3.jpg?imageView2/1/w/__width__/h/__height__
# - http://7te9fe.com1.z0.glb.clouddn.com/bgimg_4.jpg?imageView2/1/w/__width__/h/__height__
# - http://7te9fe.com1.z0.glb.clouddn.com/bgimg_5.jpg?imageView2/1/w/__width__/h/__height__

vegasConfig:
  # more about config http://vegas.jaysalvat.com/documentation/settings/
  # animation: 'random'
  # transition: 'swirlRight'
  preload­Image: true
  transition:
    # - slideLeft2
    # - slideRight2
    # - zoomIn
    # - swirLeft
    # - swirRight
    - flash
    # - flash2
  timer: true
  delay: 10000
  shuffle: true
  count: 12

unsplashConfig:
  # more about config on https://unsplash.it/
  # blur: true
  gravity: 'center' # north, east, south, west, center
  # greyscale: true

avatar: https://avatars2.githubusercontent.com/u/2735087?s=60&u=775d4033139cae6b23c593bcf59fa433224ba4e3&v=4

# do not like fancybox, set this as false, this will turn it off
fancybox: true

# set the visibility of hide button in left bottom.
hideButtonVisibility: true
